# Workflow name
name: Build Docker and Push to Registries

# Run only on new tags being pushed
on:
  push:
    tags:
      - 'v*.*.*'

# Define a single job named build
jobs:
  build:
    # Run job on Ubuntu runner
    runs-on: ubuntu-latest
    # Job Steps
    steps:
      # Step 1 - Checkout the Repository
      - name: 1 - Checkout Repository
        uses: actions/checkout@v4

      # Step 2 - Log In to GitHub Container Registry
      - name: 2 - Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3 - Log In to Azure Container Registry
      - name: 3 - Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 4 - Build and Push Docker Image
      - name: 4 - Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
            ${{ secrets.ACR_LOGIN_SERVER }}/${{ github.repository_owner }}/deployment-example:${{ github.ref_name }}
            ${{ secrets.ACR_LOGIN_SERVER }}/${{ github.repository_owner }}/deployment-example:latest

      # Step 5 - Make Release on GitHub
      - name: 5 - Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true